In [2]:
import pandas as pd
pd.set_option('display.max_columns', None)
from datetime import datetime

In [65]:


basic = pd.read_csv("virginia_basic.csv").sort_values(by="Document Nbr").reset_index()
basic = basic[(basic['Crash Severity'] == "A") | (basic['Crash Severity'] == "K")]
detail = pd.read_csv("virginia_detail.csv").sort_values(by="Document_Nbr").reset_index()

/var/folders/0r/74g1680s6rz9r8mbc5tx0_0c0000gn/T/ipykernel_10229/691132548.py:3: DtypeWarning: Columns (0: Bike_VehicleNumber, 1: Bike_Age) have mixed types. Specify dtype option on import or set low_memory=False.
  detail = pd.read_csv("virginia_detail.csv").sort_values(by="Document_Nbr").reset_index()

In [17]:
basic = pd.read_csv("virginia_basic.csv").sort_values(by="Document Nbr").reset_index()
detail = pd.read_csv("virginia_detail.csv").sort_values(by="Document_Nbr").reset_index()

/var/folders/0r/74g1680s6rz9r8mbc5tx0_0c0000gn/T/ipykernel_15225/1902167726.py:2: DtypeWarning: Columns (0: Bike_VehicleNumber, 1: Bike_Age) have mixed types. Specify dtype option on import or set low_memory=False.
  detail = pd.read_csv("virginia_detail.csv").sort_values(by="Document_Nbr").reset_index()

In [18]:
basic = basic[(basic['Crash Severity'] == "A") | (basic['Crash Severity'] == "K")]
detail = detail[detail.index.isin(basic.index)]
basic.to_csv("basic.csv")
detail.to_csv("detail.csv")

In [15]:
basic

,index,OBJECTID,Document Nbr,Local Case CD,Crash Year,Crash Date,Crash Military Time,Crash Severity,K_People,A_People,B_People,C_People,Persons Injured,Pedestrians Killed,Pedestrians Injured,Vehicle Count,Collision Type,Weather Condition,Light Condition,Roadway Surface Condition,Relation To Roadway,Roadway Alignment,Roadway Surface Type,Roadway Defect,Roadway Description,Intersection Type,Traffic Control Type,Traffic Control Status,Work Zone Related,Work Zone Location,Work Zone Type,School Zone,First Harmful Event,First Harmful Event Loc,Route or Street Name,Alcohol?,UnBelted?,Bike?,Distracted?,Animal Related?,Drowsy?,Drug Related?,Guardrail Related?,Hit & Run?,Large Vehicle?,Motorcycle?,Pedestrian?,Max Speed Diff,Speed?,RoadDeparture Type,Intersection Analysis,Senior Driver?,Young Driver?,Mainline?,Night?,VDOT District,Juris Code,Physical Juris Name,Functional Class,Facility Type,Area Type,SYSTEM,VSP,Ownership,Planning District,MPO Name,RTE Name,RNS MP,Node,Node Offset (ft),LAT,LON,x,y
26,99782,99783,170015080,DIV417000076,2017,1/1/2017 5:00:00 AM,930,A,0,1,0,0,1,0,0,1,9,1,2,2,8,3,2,1,1,1,7,1,2,0,0,3,2,4,ROUTE 619,0,0,0,0,1,0,0,0,0,0,0,0,NaN,0,2,0,0,0,1,0,1,84,84,MIC,TUD,0,3,4,1,1,NaN,R-VA084SC00619SB,13.68,NaN,NaN,36.786495,-82.587143,-82.587143,36.786495
40,10162,10163,170015121,317000007,2017,1/1/2017 5:00:00 AM,46,A,0,1,0,0,1,0,0,2,1,1,4,1,9,1,2,1,2,4,3,1,2,0,0,3,30,1,RT 501,0,1,0,1,0,0,0,0,1,0,0,0,20.0,1,0,2,0,0,1,1,3,130,130,MIA,TWD,1,4,3,3,13,NaN,R-VA US00501SB,14.61,368641.0,121.00,36.735159,-78.918238,-78.918238,36.735159
79,49301,49302,170025032,2017-000005,2017,1/1/2017 5:00:00 AM,421,A,0,1,0,0,1,0,0,1,9,1,5,1,8,1,2,1,1,1,1,6,2,0,0,3,1,2,ROUTE 632 ISLINGTON ROAD,1,1,0,0,0,0,0,0,0,0,0,0,10.0,1,1,0,0,0,1,1,6,79,79,LOC,TUD,0,3,1,1,17,NaN,R-VA079SC00632NB,2.23,NaN,NaN,37.941180,-76.755507,-76.755507,37.941180
81,40826,40827,170025035,DIV417000236,2017,1/2/2017 5:00:00 AM,145,A,0,1,1,0,2,0,0,1,9,5,5,2,9,1,2,1,2,3,6,1,2,0,0,3,5,4,ROUTE 11,0,1,0,0,0,0,1,1,0,0,0,0,25.0,1,0,1,0,0,1,1,1,86,86,MIC,TWD,1,3,4,1,3,NaN,R-VA086SC00622NB,4.86,606528.0,30.04,36.864789,-81.435776,-81.435776,36.864789
87,39527,39528,170025053,201701010322,2017,1/1/2017 5:00:00 AM,2040,A,0,2,1,0,3,0,0,2,3,1,5,1,8,4,2,1,1,1,6,1,2,0,0,3,20,1,JESSUP RD,1,1,0,1,0,0,0,0,0,0,0,0,NaN,0,3,0,0,0,1,1,4,20,20,MAC,TUD,1,3,1,1,"15,19",RICH,R-VA020SC00643WB,1.84,1151221.0,441.09,37.443831,-77.492373,-77.492373,37.443831
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1121875,1115423,1115424,261040177,02601481,2026,1/15/2026 5:00:00 AM,1518,A,0,1,0,0,1,0,0,2,1,1,2,1,9,1,2,1,4,3,9,1,2,0,0,3,20,1,WOODROW WILSON PKWY,0,0,0,1,0,0,0,0,0,0,0,0,NaN,0,0,2,0,0,0,0,8,132,132,OFE,OUD,1,4,3,3,6,SAW,R-VA SR00262SB RMP008.00A,0.22,745090.0,372.57,38.181670,-79.096640,-79.096640,38.181670
1121906,1115916,1115917,261040234,02605029,2026,2/17/2026 5:00:00 AM,1448,A,0,1,0,1,2,0,0,2,2,1,2,1,8,1,2,1,1,1,3,1,2,0,0,3,20,1,RICHMOND AVE,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,1,0,1,0,8,132,132,OPA,TWD,1,4,3,3,6,SAW,R-VA US00250WB,59.34,NaN,NaN,38.136070,-79.044560,-79.044560,38.136070
1121953,1119720,1119721,261240204,20260130205,2026,1/13/2026 5:00:00 AM,1718,A,0,1,0,0,1,0,0,1,9,9,4,1,8,3,2,1,3,1,6,1,2,0,0,3,3,1,EDSALL RD & WINTER VIEW DR,0,0,0,1,0,1,0,0,0,0,0,0,NaN,0,0,1,1,0,1,1,9,29,29,MIA,TWD,1,3,7,1,8,NOVA,R-VA029SC00648EB,2.42,1251885.0,2.95,38.804430,-77.144010,-77.144010,38.804430
1121957,1111810,1111811,261240216,20260460234,2026,2/15/2026 5:00:00 AM,2306,A,0,1,1,0,2,0,0,2,3,5,4,2,9,1,2,1,3,4,3,1,2,0,0,3,20,1,COLUMBIA PIKE & GALLOWS RD,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,1,0,1,1,1,9,29,29,OPA,TWD,1,2,7,1,8,NOVA,R-VA SR00244WB,0.61,1033943.0,3.00,38.834570,-77.186210,-77.186210,38.834570
1121983,1111254,1111255,261270206,20260430285,2026,2/12/2026 5:00:00 AM,2045,A,0,1,0,0,1,0,1,1,12,1,4,1,10,1,2,1,2,4,3,1,2,0,0,3,19,1,8300 richmond hwy,1,0,0,0,0,0,0,0,1,0,0,1,NaN,0,0,1,0,0,1,1,9,29,29,OPA,TUD,1,2,7,1,8,NOVA,R-VA US00001SB,186.35,269402.0,176.55,38.733060,-77.100540,-77.100540,38.733060

In [16]:
detail

,index,OBJECTID,Document_Nbr,Crash_Year,Crash_Severity,Driver_VehicleNumber,Driver_InjuryType,Driver_Age,Driver_Gender,Driver_Action_Type_Cd,Driver_Airbag_Deployment,Driver_Alcohol_Test_Type_Cd,Driver_Condition_Type_Cd,Driver_Distraction_Type_Cd,Driver_Drinking_Type_Cd,Driver_Drug_Use_Cd,Driver_Ejected_From_Vehicle,Driver_Ems_Transport_Ind,Driver_Fled_Scene_Ind,Driver_Safety_Equip_Used,Driver_Vis_Obscured_Type_Cd,Summons_Issued_Cd,Vehiclenumber,Vehicle_Body_Type_Cd,Vehicle_Make_Nm,Vehicle_Maneuver_Type_Cd,Vehicle_Model_Nm,Vehicle_Year_Nbr,Comm_Cargo_Body_Type_Cd,Comm_Vehicle_Body_Type_Cd,Speed_Before,Speed_Posted,Speed_Max_Safe,First_Crash_Event_Cd,Second_Crash_Event_Cd,Third_Crash_Event_Cd,Fourth_Crash_Event_Cd,Most_Harmful_Crash_Event_Cd,Initial_Veh_Impact_Area_Cd,Direction_Of_Travel_Cd,Pass_vehiclenumber,Pass_InjuryType,Pass_age,Pass_gender,Pass_Safety_Equip_Used,Pass_Airbag_Deployment,Pass_Ejected_From_Vehicle,Pass_Ems_Transport_Ind,Bike_VehicleNumber,Bike_InjuryType,Bike_Age,Bike_Gender,Ped_Number,Ped_InjuryType,PED_Age,Ped_Gender,Ped_Action,Ped_Drink,Ped_Cond,Ped_Al_Test,Ped_Drug,Ped_Rflct
26,107691,107692,170015080,2017,A,1,A,41,Male,32. Avoiding Animal,1. Deployed - Front,n/a,1. No Defects,14. No Distraction,1. No Drinking,2. No,1. Not Ejected,Yes,No,3. Lap and Shoulder Belt,1. Not Obscured,2. No,1,1. Passenger car,VOLKSWAGON,9. Ran Off Road - Right,PASSAT,2016,n/a,n/a,40,40,40,28. Ran Off Road,2. Trees,n/a,n/a,2. Trees,12,South,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,94277,94278,170015121,2017,A,1;2,PDO;PDO,29;21,Male;Male,39. Eluding Police;1. No Improper Action,1. Deployed - Front;2. Not Deployed,4. No Test;4. No Test,1. No Defects;1. No Defects,11. Other;14. No Distraction,6. Unknown;1. No Drinking,3. Unknown;2. No,1. Not Ejected;1. Not Ejected,No;No,Yes;No,8. No Restraint Used;3. Lap and Shoulder Belt,1. Not Obscured;1. Not Obscured,3. Pending;2. No,1;2,1. Passenger car;1. Passenger car,HYUNDAI;CHEVROLET,13. Passing;1. Going Straight Ahead,ELANTRA;MALIBU,2000;2011,n/a; n/a,n/a; n/a,65;45,45;45,45;45,20. Motor Vehicle In Transport;20. Motor Vehic...,28. Ran Off Road; n/a,13. Curb; n/a,30. Overturn (Rollover); n/a,30. Overturn (Rollover);20. Motor Vehicle In T...,12;6,South;South,1,A,28,Female,8. No Restraint Used,1. Deployed - Front,1. Not Ejected,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,62286,62287,170025032,2017,A,1,A,34,Male,40. Fail to Maintain Proper Control,1. Deployed - Front,4. No Test,8. Other,14. No Distraction,2. Drinking - Obviously Drunk,3. Unknown,1. Not Ejected,Yes,No,8. No Restraint Used,1. Not Obscured,1. Yes,1,1. Passenger car,HYUNDAI,10. Ran Off Road - Left,SONATA,2010,n/a,n/a,55,45,45,28. Ran Off Road,1. Bank Or Ledge,28. Ran Off Road,3. Utility Pole,3. Utility Pole,1,East,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,8654,8655,170025035,2017,A,1,B,47,Male,39. Eluding Police,1. Deployed - Front,n/a,1. No Defects,14. No Distraction,1. No Drinking,1. Yes,1. Not Ejected,Yes,No,8. No Restraint Used,1. Not Obscured,1. Yes,1,1. Passenger car,MITSUBISHI,10. Ran Off Road - Left,ECLIPSE,2001,n/a,n/a,75,50,50,28. Ran Off Road,5. Guard Rail,30. Overturn (Rollover),1. Bank Or Ledge,30. Overturn (Rollover),11,North,1,A,21,Female,3. Lap and Shoulder Belt,1. Deployed - Front,1. Not Ejected,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,82615,82616,170025053,2017,A,1;2,A;A,35;31,Male;Female,40. Fail to Maintain Proper Control;1. No Impr...,1. Deployed - Front;1. Deployed - Front,1. Blood; n/a,1. No Defects;1. No Defects,7. Eyes Not on Road;14. No Distraction,2. Drinking - Obviously Drunk;1. No Drinking,3. Unknown;3. Unknown,2. Partially Ejected;1. Not Ejected,Yes;Yes,No;No,8. No Restraint Used;3. Lap and Shoulder Belt,1. Not Obscured;1. Not Obscured,1. Yes;2. No,1;2,1. Passenger car;22. Truck (SUV),HONDA;JEEP,1. Going Straight Ahead;1. Going Straight Ahead,ACCORD;GRAND CHEROKEE,1996;1999,n/a; n/a,n/a; n/a,n/a;n/a,35;35,35;35,36. Cross Centerline;20. Motor Vehicle In Tran...,20. Motor Vehicle In Transport; n/a,n/a; n/a,n/a; n/a,20. Motor Vehicle In Transport;20. Motor Vehic...,12;12,East;West,2,B,12,Male,3. Lap and Shoulder Belt,1. Deployed - Front,1. Not Ejected,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1121875,1108664,1108665,261040177,2026,A,1;2,PDO;A,42;64,Male;Female,12. Following Too Close;1. No Improper Action,2. Not Deployed;2. Not Deployed,4. No Test;4. No Test,1. No Defects;1. No Defects,7. Eyes Not on Road;14. No Distraction,1. No Drinking;1. No Drinking,2. No;2. No,1. Not Ejected;1. Not Ejected,No;No,No;No,3. Lap and Shoulder Belt;3. Lap and Shoulder Belt,12. Sun or Headlight Glare;1. Not Obscured,1. Yes;2. No,1;2,3. Van;1. Passenger car,CHRY;NISS,2. Making Right Turn;8. Stopped in Traffic Lane,VOYAGER;ROGUE,2023;2017,n/a; n/a,n/a; n/a,5;0,35;35,35;35,20. Motor Vehicle In Transport;20. Motor Vehic...,n/a; n/a,n/a; n/a,n/a; n/a,20. Motor Vehicle In Transport;20. Motor Vehic...,1;7,East;East,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1121906,1120485,1120486,261040234,2026,A,1;2,A;PDO,78;71,Male;Male,21. Disregarded Traffic Signal;1. No Improper ...,8. Deployed - Combination;2. Not Deployed,4. No Test;4. No Test,1. No Defects;1. No Defects,14. No Distraction;14. No Distraction,1. No Drinking;1. No Drinking,2. No;2. No,1. Not Ejected;1. Not Ejected,No;No,No;No,3. Lap and Shoulder Belt;3. Lap and Shoulder Belt,1. Not Obscured;1. Not Obscured,1. Yes;2. No,1;2,1. Passenger car;2. Pick-up Truck,TOYT;CHEV,1. Going Straight Ahead;3. Making Left Turn,COROLLA;SILVERADO,2010;2018,n/a; n/a,n/a; n/a,30;5,35;35,35;35,20. Motor Vehicle In Transport;20. Motor Vehic...,n/a; n/a,n/a; n/a,n/a; n/a,20. Motor Vehicle In Transport;20. Motor Vehic...,12;4,West;North,1,C,26,Male,3. Lap and Shoulder Belt,8. Deployed - Combination,1. Not Ejected,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1121953,1111224,1111225,261240204,2026,A,1,A,67,Female,1. No Improper Action,1. Deployed - Front,4. No Test,6. Fatigued,2. Driver Fatigue,1. No Drinking,3. Unknown,1. Not Ejected,Yes,No,3. Lap and Shoulder Belt,1. Not Obscured,2. No,1,22. Truck (SUV),SUBARU,1. Going Straight Ahead,OUTBACK,2020,n/a,n/a,35,35,35,3. Utility Pole,n/a,n/a,n/a,3. Utility Pole,12,East,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1121957,1109797,1109798,261240216,2026,A,1;2,PDO;B,16;45,Male;Male,21. Disregarded Traffic Signal;1. No Improper ...,8. Deployed - Combination;8. Deployed - Combin...,4. No Test;4. No Test,1. No Defects;1. No Defects,14. No Distraction;14. No Distraction,1. No Drinking;1. No Drinking,3. Unknown;3. Unknown,1. Not Ejected;1. Not Ejected,No;Yes,No;No,3. Lap and Shoulder Belt;3. Lap and Shoulder Belt,"2. Rain, Snow, etc. on Windshield;1. Not Obscured",2. No;2. No,1;2,22. Truck (SUV);22. Truck (SUV),LEXUS;CHEVROLET,1. Going Straight Ahead;3. Making Left Turn,RX350;TRAX,2019;2022,n/a; n/a,n/a; n/a,35;20,35;35,35;35,20. Motor Vehicle In Transport;20. Motor Vehic...,n/a; n/a,n/a; n/a,n/a; n/a,20. Motor Vehicle In Transport;20. Motor Vehic...,12;12,West;South,2,A,28,Female,3. Lap and Shoulder Belt,8. Deployed - Combination,1. Not Ejected,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1121983,1112289,1112290,261270206,2026,A,1,PDO,NaN,n/a,34. Hit and Run,5. Unknown,n/a,n/a,n/a,6. Unknown,n/a,1. Not Ejected,No,Yes,9. n/a,n/a,2. No,1,2. Pick-up Truck,GENERAL MOTORS CORP.,1. Going Straight Ahead,SIERRA,2025,n/a,n/a,35,35,35,19. Ped,n/a,n/a,n/a,19. Ped,12,South,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,A,49,Female,15. Walking In Roadway Against Traffic - Sidew...,5. Drinking - Not Known Whether Impaired,n/a,4. No Test,n/a,2. No

In [66]:
z = 0
for x in basic.index:
    doc = int(basic['Document Nbr'][x])
    doc2 = int(detail['Document_Nbr'][x])
    if doc != doc2:
        z += 1

In [76]:
basic['Crash Year'].unique()

array([2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026])

In [73]:
detail[detail['Document_Nbr']==203355094]

,index,OBJECTID,Document_Nbr,Crash_Year,Crash_Severity,Driver_VehicleNumber,Driver_InjuryType,Driver_Age,Driver_Gender,Driver_Action_Type_Cd,Driver_Airbag_Deployment,Driver_Alcohol_Test_Type_Cd,Driver_Condition_Type_Cd,Driver_Distraction_Type_Cd,Driver_Drinking_Type_Cd,Driver_Drug_Use_Cd,Driver_Ejected_From_Vehicle,Driver_Ems_Transport_Ind,Driver_Fled_Scene_Ind,Driver_Safety_Equip_Used,Driver_Vis_Obscured_Type_Cd,Summons_Issued_Cd,Vehiclenumber,Vehicle_Body_Type_Cd,Vehicle_Make_Nm,Vehicle_Maneuver_Type_Cd,Vehicle_Model_Nm,Vehicle_Year_Nbr,Comm_Cargo_Body_Type_Cd,Comm_Vehicle_Body_Type_Cd,Speed_Before,Speed_Posted,Speed_Max_Safe,First_Crash_Event_Cd,Second_Crash_Event_Cd,Third_Crash_Event_Cd,Fourth_Crash_Event_Cd,Most_Harmful_Crash_Event_Cd,Initial_Veh_Impact_Area_Cd,Direction_Of_Travel_Cd,Pass_vehiclenumber,Pass_InjuryType,Pass_age,Pass_gender,Pass_Safety_Equip_Used,Pass_Airbag_Deployment,Pass_Ejected_From_Vehicle,Pass_Ems_Transport_Ind,Bike_VehicleNumber,Bike_InjuryType,Bike_Age,Bike_Gender,Ped_Number,Ped_InjuryType,PED_Age,Ped_Gender,Ped_Action,Ped_Drink,Ped_Cond,Ped_Al_Test,Ped_Drug,Ped_Rflct
481496,481496,481497,203355094,2020,A,1;2,A;PDO,15;25,Female;Female,8. Cutting In;1. No Improper Action,3. n/a;2. Not Deployed,n/a;4. No Test,1. No Defects; n/a,n/a; n/a,1. No Drinking;1. No Drinking,n/a;2. No,1. Not Ejected;1. Not Ejected,No;No,No;No,8. No Restraint Used;3. Lap and Shoulder Belt,1. Not Obscured;1. Not Obscured,2. No;2. No,1;2,9. Bicycle;1. Passenger car,MERZ,1. Going Straight Ahead;1. Going Straight Ahead,ML350,2008,n/a; n/a,n/a; n/a,5;25,25;25,25;25,20. Motor Vehicle In Transport;22. Bicycle,n/a; n/a,n/a; n/a,n/a; n/a,20. Motor Vehicle In Transport;22. Bicycle,11;1,South;South,1,A,14,Male,9. n/a,3. n/a,1. Not Ejected,Yes,1.0,A,15.0,Female,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
basic[basic["Document Nbr"]==172705368]

,OBJECTID,Document Nbr,Local Case CD,Crash Year,Crash Date,Crash Military Time,Crash Severity,K_People,A_People,B_People,C_People,Persons Injured,Pedestrians Killed,Pedestrians Injured,Vehicle Count,Collision Type,Weather Condition,Light Condition,Roadway Surface Condition,Relation To Roadway,Roadway Alignment,Roadway Surface Type,Roadway Defect,Roadway Description,Intersection Type,Traffic Control Type,Traffic Control Status,Work Zone Related,Work Zone Location,Work Zone Type,School Zone,First Harmful Event,First Harmful Event Loc,Route or Street Name,Alcohol?,UnBelted?,Bike?,Distracted?,Animal Related?,Drowsy?,Drug Related?,Guardrail Related?,Hit & Run?,Large Vehicle?,Motorcycle?,Pedestrian?,Max Speed Diff,Speed?,RoadDeparture Type,Intersection Analysis,Senior Driver?,Young Driver?,Mainline?,Night?,VDOT District,Juris Code,Physical Juris Name,Functional Class,Facility Type,Area Type,SYSTEM,VSP,Ownership,Planning District,MPO Name,RTE Name,RNS MP,Node,Node Offset (ft),LAT,LON,x,y
104170,104171,172705368,317072542,2017,9/23/2017 4:00:00 AM,1334,A,0,1,0,0,1,0,0,1,9,1,2,1,8,4,2,1,1,1,7,1,2,0,0,3,5,4,RT130,0,1,0,0,0,0,0,1,0,0,0,0,5.0,1,2,0,1,0,1,0,3,5,5,MIA,TUD,0,2,3,1,11,NaN,R-VA US00501NB,98.99,NaN,NaN,37.608287,-79.42671,-79.42671,37.608287

In [51]:
detail[detail["Document_Nbr"]==172705368]

,OBJECTID,Document_Nbr,Crash_Year,Crash_Severity,Driver_VehicleNumber,Driver_InjuryType,Driver_Age,Driver_Gender,Driver_Action_Type_Cd,Driver_Airbag_Deployment,Driver_Alcohol_Test_Type_Cd,Driver_Condition_Type_Cd,Driver_Distraction_Type_Cd,Driver_Drinking_Type_Cd,Driver_Drug_Use_Cd,Driver_Ejected_From_Vehicle,Driver_Ems_Transport_Ind,Driver_Fled_Scene_Ind,Driver_Safety_Equip_Used,Driver_Vis_Obscured_Type_Cd,Summons_Issued_Cd,Vehiclenumber,Vehicle_Body_Type_Cd,Vehicle_Make_Nm,Vehicle_Maneuver_Type_Cd,Vehicle_Model_Nm,Vehicle_Year_Nbr,Comm_Cargo_Body_Type_Cd,Comm_Vehicle_Body_Type_Cd,Speed_Before,Speed_Posted,Speed_Max_Safe,First_Crash_Event_Cd,Second_Crash_Event_Cd,Third_Crash_Event_Cd,Fourth_Crash_Event_Cd,Most_Harmful_Crash_Event_Cd,Initial_Veh_Impact_Area_Cd,Direction_Of_Travel_Cd,Pass_vehiclenumber,Pass_InjuryType,Pass_age,Pass_gender,Pass_Safety_Equip_Used,Pass_Airbag_Deployment,Pass_Ejected_From_Vehicle,Pass_Ems_Transport_Ind,Bike_VehicleNumber,Bike_InjuryType,Bike_Age,Bike_Gender,Ped_Number,Ped_InjuryType,PED_Age,Ped_Gender,Ped_Action,Ped_Drink,Ped_Cond,Ped_Al_Test,Ped_Drug,Ped_Rflct
71119,71120,172705368,2017,A,1,A,71,Male,1. No Improper Action,1. Deployed - Front,4. No Test,8. Other,14. No Distraction,6. Unknown,3. Unknown,1. Not Ejected,NotProvided,No,8. No Restraint Used,1. Not Obscured,2. No,1,1. Passenger car,NISSAN,9. Ran Off Road - Right,MAXIMA,2001,n/a,n/a,45,55,40,28. Ran Off Road,5. Guard Rail,1. Bank Or Ledge,2. Trees,1. Bank Or Ledge,1,East,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
detail[3046:3047]

,OBJECTID,Document_Nbr,Crash_Year,Crash_Severity,Driver_VehicleNumber,Driver_InjuryType,Driver_Age,Driver_Gender,Driver_Action_Type_Cd,Driver_Airbag_Deployment,Driver_Alcohol_Test_Type_Cd,Driver_Condition_Type_Cd,Driver_Distraction_Type_Cd,Driver_Drinking_Type_Cd,Driver_Drug_Use_Cd,Driver_Ejected_From_Vehicle,Driver_Ems_Transport_Ind,Driver_Fled_Scene_Ind,Driver_Safety_Equip_Used,Driver_Vis_Obscured_Type_Cd,Summons_Issued_Cd,Vehiclenumber,Vehicle_Body_Type_Cd,Vehicle_Make_Nm,Vehicle_Maneuver_Type_Cd,Vehicle_Model_Nm,Vehicle_Year_Nbr,Comm_Cargo_Body_Type_Cd,Comm_Vehicle_Body_Type_Cd,Speed_Before,Speed_Posted,Speed_Max_Safe,First_Crash_Event_Cd,Second_Crash_Event_Cd,Third_Crash_Event_Cd,Fourth_Crash_Event_Cd,Most_Harmful_Crash_Event_Cd,Initial_Veh_Impact_Area_Cd,Direction_Of_Travel_Cd,Pass_vehiclenumber,Pass_InjuryType,Pass_age,Pass_gender,Pass_Safety_Equip_Used,Pass_Airbag_Deployment,Pass_Ejected_From_Vehicle,Pass_Ems_Transport_Ind,Bike_VehicleNumber,Bike_InjuryType,Bike_Age,Bike_Gender,Ped_Number,Ped_InjuryType,PED_Age,Ped_Gender,Ped_Action,Ped_Drink,Ped_Cond,Ped_Al_Test,Ped_Drug,Ped_Rflct
3046,3047,171145071,2017,B,1,NaN,NaN,n/a,18. Improper Backing,n/a,n/a,9. Unknown,n/a,6. Unknown,3. Unknown,n/a,NotProvided,Yes,n/a,n/a,n/a,1,n/a,NaN,12. Backing,NaN,NaN,n/a,n/a,5,15,15,19. Ped,n/a,n/a,n/a,19. Ped,6,South,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,B,29,Male,17. Standing In Roadway,1. No Drinking,1. No Defects,n/a,2. No,2. No

In [6]:
basic

,OBJECTID,Document Nbr,Local Case CD,Crash Year,Crash Date,Crash Military Time,Crash Severity,K_People,A_People,B_People,C_People,Persons Injured,Pedestrians Killed,Pedestrians Injured,Vehicle Count,Collision Type,Weather Condition,Light Condition,Roadway Surface Condition,Relation To Roadway,Roadway Alignment,Roadway Surface Type,Roadway Defect,Roadway Description,Intersection Type,Traffic Control Type,Traffic Control Status,Work Zone Related,Work Zone Location,Work Zone Type,School Zone,First Harmful Event,First Harmful Event Loc,Route or Street Name,Alcohol?,UnBelted?,Bike?,Distracted?,Animal Related?,Drowsy?,Drug Related?,Guardrail Related?,Hit & Run?,Large Vehicle?,Motorcycle?,Pedestrian?,Max Speed Diff,Speed?,RoadDeparture Type,Intersection Analysis,Senior Driver?,Young Driver?,Mainline?,Night?,VDOT District,Juris Code,Physical Juris Name,Functional Class,Facility Type,Area Type,SYSTEM,VSP,Ownership,Planning District,MPO Name,RTE Name,RNS MP,Node,Node Offset (ft),LAT,LON,x,y
0,1,170785244,20170613,2017,3/15/2017 4:00:00 AM,845,O,0,0,0,0,0,0,0,2,4,1,2,1,9,1,2,1,2,4,3,1,2,0,0,1,20,1,16TH STREET,0,0,0,1,0,0,0,0,0,0,0,0,NaN,0,0,2,1,0,1,0,5,121,121,LOC,TUD,1,5,5,3,23,HAMP,S-VA121PR IVY AVE,0.59,731559.0,48.58,36.975935,-76.415070,-76.415070,36.975935
1,2,173135321,201711030319,2017,11/3/2017 4:00:00 AM,1718,O,0,0,0,0,0,0,0,2,2,1,2,1,9,1,2,1,1,4,4,1,2,0,0,3,20,1,BELMONT RD,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,1,0,0,1,0,4,20,20,MIA,TUD,1,3,1,1,"15,19",RICH,R-VA020SC00651WB,9.83,203463.0,9.78,37.455126,-77.509985,-77.509985,37.455126
2,3,173035461,17101483,2017,10/30/2017 4:00:00 AM,734,O,0,0,0,0,0,0,0,2,1,1,2,1,9,1,2,1,2,4,3,1,2,0,0,3,20,1,STONEWALL JACKSON HIGHWAY,0,0,0,0,0,0,0,0,0,1,0,0,NaN,0,0,1,0,0,1,0,8,112,112,MIA,TWD,0,2,2,1,7,NaN,R-VA US00340NB,94.13,713190.0,84.94,38.908610,-78.197568,-78.197568,38.908610
3,4,172925444,2017-1511,2017,10/19/2017 4:00:00 AM,511,O,0,0,0,0,0,0,0,1,10,1,5,1,8,1,2,1,2,1,6,1,2,0,0,3,23,1,RT 301/RICHMOND TPKE,0,0,0,0,1,0,0,0,0,0,0,0,NaN,0,0,1,0,0,1,1,6,16,16,MIA,TWD,0,2,1,1,16,NaN,R-VA US00301NB,111.74,1168608.0,174.41,38.034672,-77.341817,-77.341817,38.034672
4,5,172245260,20170012563,2017,8/12/2017 4:00:00 AM,218,O,0,0,0,0,0,0,0,2,2,1,4,1,10,1,2,1,1,4,3,1,2,0,0,3,20,1,E WASHINGTON ST,1,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,2,0,0,1,1,5,133,133,MIA,TUD,1,4,5,3,23,HAMP,R-VA SR00337WB,1.29,469440.0,18.79,36.726418,-76.577223,-76.577223,36.726418
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1121983,1121984,260570082,2026-00011376,2026,2/25/2026 5:00:00 AM,1159,O,0,0,0,0,0,0,0,2,2,1,2,1,9,1,2,1,1,4,4,1,2,0,0,3,20,1,BENT MOUNTAIN RD,0,0,0,0,0,0,0,0,0,1,0,0,NaN,0,0,1,1,0,1,0,2,80,80,MIA,TUD,0,2,6,1,5,NaN,R-VA US00221SB,83.36,571045.0,1.88,37.167110,-80.115460,-80.115460,37.167110
1121984,1121985,260350163,DIV726011364,2026,2/4/2026 5:00:00 AM,650,O,0,0,0,0,0,0,0,2,5,1,2,3,8,2,2,1,1,1,6,1,2,0,0,3,20,1,BULL RUN POST OFFICE ROAD,0,0,0,0,0,0,0,0,0,1,0,0,NaN,0,0,0,0,0,1,0,9,29,29,MAC,TUD,1,3,7,1,8,NOVA,R-VA029SC00621WB,2.97,NaN,NaN,38.836720,-77.494870,-77.494870,38.836720
1121985,1121986,260350191,202602040174,2026,2/4/2026 5:00:00 AM,1014,B,0,0,1,0,1,0,0,2,2,1,2,1,9,1,2,1,2,3,3,1,2,0,0,3,20,1,FOREST HILL AVENUE,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,2,0,0,1,0,4,127,127,MIA,TWD,1,5,1,3,15,RICH,S-VA127NP FOREST HILL AVE,4.24,1056334.0,39.06,37.537210,-77.530420,-77.530420,37.537210
1121986,1121987,260280023,DIV126007872,2026,1/28/2026 5:00:00 AM,600,O,0,0,0,0,0,0,0,1,16,1,1,4,8,1,2,7,3,1,6,1,2,0,0,3,28,1,I-64 EB,0,0,0,0,0,0,0,0,0,0,0,0,10.0,1,3,0,0,0,1,0,4,43,43,INT,TWD,1,1,1,1,15,RICH,R-VA IS00064EB,176.81,NaN,NaN,37.661710,-77.626930,-77.626930,37.661710
1121987,1121988,260380024,2602-0060,2026,2/6/2026 5:00:00 AM,0,B,0,0,1,0,1,0,0,1,4,1,3,2,9,1,2,1,3,4,3,1,2,0,0,1,28,2,rixeyville road,0,0,0,0,0,0,0,0,0,0,0,0,10.0,1,0,0,0,1,1,0,7,23,23,MIA,TWD,1,2,2,1,9,NaN,R-VA SR00229SB,1.36,NaN,NaN,38.498670,-77.991630,-77.991630,38.498670

,OBJECTID,Document_Nbr,Crash_Year,Crash_Severity,Driver_VehicleNumber,Driver_InjuryType,Driver_Age,Driver_Gender,Driver_Action_Type_Cd,Driver_Airbag_Deployment,Driver_Alcohol_Test_Type_Cd,Driver_Condition_Type_Cd,Driver_Distraction_Type_Cd,Driver_Drinking_Type_Cd,Driver_Drug_Use_Cd,Driver_Ejected_From_Vehicle,Driver_Ems_Transport_Ind,Driver_Fled_Scene_Ind,Driver_Safety_Equip_Used,Driver_Vis_Obscured_Type_Cd,Summons_Issued_Cd,Vehiclenumber,Vehicle_Body_Type_Cd,Vehicle_Make_Nm,Vehicle_Maneuver_Type_Cd,Vehicle_Model_Nm,Vehicle_Year_Nbr,Comm_Cargo_Body_Type_Cd,Comm_Vehicle_Body_Type_Cd,Speed_Before,Speed_Posted,Speed_Max_Safe,First_Crash_Event_Cd,Second_Crash_Event_Cd,Third_Crash_Event_Cd,Fourth_Crash_Event_Cd,Most_Harmful_Crash_Event_Cd,Initial_Veh_Impact_Area_Cd,Direction_Of_Travel_Cd,Pass_vehiclenumber,Pass_InjuryType,Pass_age,Pass_gender,Pass_Safety_Equip_Used,Pass_Airbag_Deployment,Pass_Ejected_From_Vehicle,Pass_Ems_Transport_Ind,Bike_VehicleNumber,Bike_InjuryType,Bike_Age,Bike_Gender,Ped_Number,Ped_InjuryType,PED_Age,Ped_Gender,Ped_Action,Ped_Drink,Ped_Cond,Ped_Al_Test,Ped_Drug,Ped_Rflct
0,1,171125248,2017,A,1,A,25,Female,40. Fail to Maintain Proper Control,3. n/a,n/a,9. Unknown,14. No Distraction,6. Unknown,3. Unknown,1. Not Ejected,Yes,No,5. Helmet,1. Not Obscured,3. Pending,1,11. Motorcycle,YAMAHA,3. Making Left Turn,R6,2013,n/a,n/a,NaN,45,45,28. Ran Off Road,n/a,n/a,n/a,28. Ran Off Road,1,North,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,173325167,2017,O,1;2,PDO;PDO,70;19,Female;Female,11. Did Not Have Right-of-Way;1. No Improper A...,2. Not Deployed;2. Not Deployed,n/a; n/a,1. No Defects;1. No Defects,14. No Distraction;14. No Distraction,1. No Drinking;1. No Drinking,2. No;2. No,1. Not Ejected;1. Not Ejected,NotProvided;NotProvided,No;No,3. Lap and Shoulder Belt;3. Lap and Shoulder Belt,1. Not Obscured;1. Not Obscured,1. Yes;2. No,1;2,1. Passenger car;1. Passenger car,TOYOTA;TOYOTA,2. Making Right Turn;1. Going Straight Ahead,CAMERY;YARIS,2017;2007,n/a; n/a,n/a; n/a,5;25,25;25,25;25,20. Motor Vehicle In Transport;20. Motor Vehic...,n/a; n/a,n/a; n/a,n/a; n/a,20. Motor Vehicle In Transport;20. Motor Vehic...,12;2,West;North,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,170705016,2017,O,1;2,PDO;PDO,42;54,Female;Female,42. Improper or Unsafe Lane Change;1. No Impro...,2. Not Deployed;2. Not Deployed,n/a; n/a,1. No Defects;1. No Defects,14. No Distraction;14. No Distraction,1. No Drinking;1. No Drinking,n/a; n/a,1. Not Ejected;1. Not Ejected,No;No,No;No,3. Lap and Shoulder Belt;3. Lap and Shoulder Belt,14. Blind Spot;1. Not Obscured,1. Yes;2. No,1;2,1. Passenger car;22. Truck (SUV),FORD;HYUNDAI,14. Changing Lanes;1. Going Straight Ahead,TAURUS;SANTA FE,2000;2004,n/a; n/a,n/a; n/a,50;50,55;55,55;55,20. Motor Vehicle In Transport;20. Motor Vehic...,n/a; n/a,n/a; n/a,n/a; n/a,20. Motor Vehicle In Transport;20. Motor Vehic...,2;10,North;North,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,172885052,2017,O,1,PDO,61,Male,40. Fail to Maintain Proper Control,2. Not Deployed,n/a,1. No Defects,14. No Distraction,1. No Drinking,2. No,1. Not Ejected,No,No,3. Lap and Shoulder Belt,1. Not Obscured,1. Yes,1,22. Truck (SUV),JEEP,9. Ran Off Road - Right,GRAND CHEROKEE,2004,n/a,n/a,40,60,60,28. Ran Off Road,5. Guard Rail,30. Overturn (Rollover),n/a,5. Guard Rail,3,South,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,171425307,2017,O,1;2,PDO;PDO,61;50,Male;Male,12. Following Too Close;1. No Improper Action,1. Deployed - Front;2. Not Deployed,n/a; n/a,1. No Defects;1. No Defects,14. No Distraction;14. No Distraction,1. No Drinking;1. No Drinking,2. No;2. No,1. Not Ejected;1. Not Ejected,No;No,No;No,3. Lap and Shoulder Belt;3. Lap and Shoulder Belt,1. Not Obscured;1. Not Obscured,1. Yes;2. No,1;2,2. Pick-up Truck;2. Pick-up Truck,Toyota;Ford,1. Going Straight Ahead;8. Stopped in Traffic ...,TACOMA;F150,1996;2011,n/a; n/a,n/a; n/a,20;0,45;45,45;0,20. Motor Vehicle In Transport;20. Motor Vehic...,n/a; n/a,n/a; n/a,n/a; n/a,20. Motor Vehicle In Transport;20. Motor Vehic...,12;6,South;South,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1121983,1121984,260080058,2026,O,1,PDO,43,Male,1. No Improper Action,2. Not Deployed,n/a,1. No Defects,14. No Distraction,1. No Drinking,2. No,1. Not Ejected,No,No,3. Lap and Shoulder Belt,1. Not Obscured,2. No,1,1. Passenger car,HOND,1. Going Straight Ahead,UEX,2014,n/a,n/a,65,65,65,23. Animal,n/a,n/a,n/a,23. Animal,12,South,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1121984,1121985,260110188,2026,O,1;2,PDO;PDO,19;57,Male;Female,2. Exceeded Speed Limit;1. No Improper Action,2. Not Deployed;2. Not Deployed,n/a; n/a,1. No Defects;1. No Defects,14. No Distraction;14. No Distraction,1. No Drinking;1. No Drinking,2. No;2. No,1. Not Ejected;1. Not Ejected,No;No,No;No,3. Lap and Shoulder Belt;3. Lap and Shoulder Belt,1. Not Obscured;1. Not Obscured,1. Yes;2. No,1;2,1. Passenger car;22. Truck (SUV),HONDA;MAZDA,1. Going Straight Ahead;1. Going Straight Ahead,CIVIC;CX-5,2025;2016,n/a; n/a,n/a; n/a,75;69,70;70,69;70,20. Motor Vehicle In Transport;20. Motor Vehic...,n/a; n/a,n/a; n/a,n/a; n/a,20. Motor Vehicle In Transport;20. Motor Vehic...,12;6,South;South,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1121985,1121986,260080175,2026,O,1,PDO,78,Male,37. Other,2. Not Deployed,4. No Test,1. No Defects,14. No Distraction,1. No Drinking,2. No,1. Not Ejected,No,No,3. Lap and Shoulder Belt,1. Not Obscured,2. No,1,23. Truck (3 Axles or More),International,1. Going Straight Ahead,Mobile Home Toter,2007,n/a,n/a,NaN,25,25,"7. Tunnel, Bridge, Underpass, Culvert, etc.",n/a,n/a,n/a,"7. Tunnel, Bridge, Underpass, Culvert, etc.",13,South,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1121986,1121987,260080278,2026,O,1;2,PDO;PDO,53;18,Female;Female,11. Did Not Have Right-of-Way;1. No Improper A...,2. Not Deployed;2. Not Deployed,4. No Test;4. No Test,1. No Defects;1. No Defects,14. No Distraction;14. No Distraction,1. No Drinking;1. No Drinking,2. No;2. No,1. Not Ejected;1. Not Ejected,No;No,No;No,n/a;3. Lap and Shoulder Belt,1. Not Obscured;1. Not Obscured,2. No;2. No,1;2,1. Passenger car;1. Passenger car,FORD;MERCEDES-BENZ,3. Making Left Turn;1. Going Straight Ahead,Fusion;E-Class,2015;2002,n/a; n/a,n/a; n/a,n/a;n/a,45;45,45;45,20. Motor Vehicle In Transport;20. Motor Vehic...,n/a; n/a,n/a; n/a,n/a; n/a,20. Motor Vehicle In Transport;20. Motor Vehic...,3;12,North;North,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1121987,1121988,260030048,2026,B,1,B,65,Male,40. Fail to Maintain Proper Control,2. Not Deployed,n/a,6. Fatigued,2. Driver Fatigue,1. No Drinking,2. No,1. Not Ejected,No,No,3. Lap and Shoulder Belt,1. Not Obscured,1. Yes,1,1. Passenger car,TOYOTA,9. Ran Off Road - Right,CAMRY,2002,n/a,n/a,70,70,70,28. Ran Off Road,14. Ditch,n/a,n/a,14. Ditch,12,South,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
def format_military_time(time_int: int) -> str:
    time_str = str(time_int).zfill(4)

    if len(time_str) > 4:
        raise ValueError(f"Invalid military time: {time_int}")

    hours = int(time_str[0:2])
    minutes = int(time_str[2:4])

    if not (0 <= hours <= 23):
        raise ValueError(f"Invalid hours: {hours}")
    if not (0 <= minutes <= 59):
        raise ValueError(f"Invalid minutes: {minutes}")

    return f"{hours:02d}:{minutes:02d}:00"

def get_injury_severity(code):
    if code == "K":
        return 4
    if code == "A":
        return 3
    if code == "B":
        return 2
    if code == "C":
        return 1
    if code == "PDO":
        return 0
    return 9

In [9]:
for x in basic.index:
    state_accident_id = basic['Document Nbr'][x]
    print(state_accident_id)
    lat = basic['LAT'][x]
    lon = basic['LON'][x]
    street_1 = basic['Route or Street Name'][x]
    date = basic['Crash Date'][x]
    month = date.split("/")[0].zfill(2)
    day = date.split("/")[1].zfill(2)
    year = date.split("/")[2].split(" ")[0]
    time = format_military_time(basic['Crash Military Time'][x])
    dt = datetime.strptime(f"{year}-{month}-{day}T{time}", "%Y-%m-%dT%H:%M:%S")
    city = basic['MPO Name'][x]
    death_count = basic['K_People'][x]
    severe_injury_count = basic['A_People'][x]
    crash_severity = basic['Crash Severity'][x]
    crash_type = detail['Most_Harmful_Crash_Event_Cd'][x]
    if pd.isnull(city):
        city = None
    else:
        city = f"{city} (Metro)"
        
    vehicles = detail['Vehiclenumber'][x].split(";")
    drivers = detail['Driver_VehicleNumber'][x] 
    if pd.isnull(drivers):
        drivers = []
    else:
        drivers = drivers.split(";")
    passengers = detail['Pass_vehiclenumber'][x] 
    if pd.isnull(passengers):
        passengers = []
    else:
        passengers = passengers.split(";")
    pedestrians = detail['Ped_Number'][x] 
    if pd.isnull(pedestrians):
        pedestrians = []
    else:
        pedestrians = pedestrians.split(";")
    bicycles = detail['Bike_VehicleNumber'][x] 
    if pd.isnull(bicycles):
        bicycles = []
    else:
        bicycles = bicycles.split(";") 

    for vehicle_number in vehicles:
        index = int(vehicle_number) - 1
        make = detail['Vehicle_Make_Nm'][x].split(";")[index]
        model = detail['Vehicle_Model_Nm'][x].split(";")[index]
        year = detail['Vehicle_Year_Nbr'][x].split(";")[index]
        body_type = detail['Vehicle_Body_Type_Cd'][x].split(";")[index]
        violation = detail['Summons_Issued_Cd'][x].split(";")[index]
        hit_run = detail['Driver_Fled_Scene_Ind'][x].split(";")[index]
    for vehicle_number in drivers:
        print(vehicle_number)
        index = int(vehicle_number) - 1
        age = detail['Driver_Age'][x].split(";")[index]
        sex = detail['Driver_Gender'][x].split(";")[index]
        inj_sev = get_injury_severity(detail['Driver_InjuryType'][x].split(";")[index])
        print(f"{age} {sex} injured? {inj_sev}")
    index = 0
    for vehicle_number in passengers:
        age = detail['Pass_age'][x].split(";")[index]
        sex = detail['Pass_age'][x].split(";")[index]
        inj_sev = get_injury_severity(detail['Pass_InjuryType'][x].split(";")[index])
        index += 1
    for pedestrian in pedestrians:
        index = pedestrian - 1
        age = detail['PED_Age'].split(";")[index]
        sex = detail['Ped_Gender'].split(";")[index]
        inj_sev = detail['Ped_InjuryType'].split(";")[index]
    index = 0
    for bike in bicycles:
        age = detail['Bike_Age'].split(";")[index]
        sex = detail['Bike_Gender'].split(";")[index]
        inj_sev = detail['Bike_InjuryType'].split(";")[index]
        index += 1
        
        
    if x > 10:
        break

170785244
1
25 Female injured? 3
173135321
1
70 Female injured? 0
2
19 Female injured? 0
173035461
1
42 Female injured? 0
2
54 Female injured? 0
172925444
1
61 Male injured? 0
172245260
1
61 Male injured? 0
2
50 Male injured? 0
172585274
1
30 Male injured? 0
2
40 Female injured? 0
173495215
1
26 Male injured? 0
2
58 Male injured? 0
170885135
1
58 Female injured? 1
2
35 Female injured? 0
170245050
1
67 Male injured? 0
2
68 Male injured? 0
173405408
1
18 Male injured? 0
173095004
1
44 Female injured? 0
2
40 Female injured? 0
172155126
1
20 Female injured? 0
2
50 Female injured? 0

In [76]:
basic['Crash Military Time'][x]

np.int64(832)

In [34]:
basic['Crash Date'][0]

'3/15/2017 4:00:00 AM'

In [37]:
basic['Crash Severity'].unique()

<StringArray>
['O', 'B', 'C', 'A', 'K']
Length: 5, dtype: str

In [10]:
detail[pd.notnull(detail['Pass_vehiclenumber'])]

,OBJECTID,Document_Nbr,Crash_Year,Crash_Severity,Driver_VehicleNumber,Driver_InjuryType,Driver_Age,Driver_Gender,Driver_Action_Type_Cd,Driver_Airbag_Deployment,Driver_Alcohol_Test_Type_Cd,Driver_Condition_Type_Cd,Driver_Distraction_Type_Cd,Driver_Drinking_Type_Cd,Driver_Drug_Use_Cd,Driver_Ejected_From_Vehicle,Driver_Ems_Transport_Ind,Driver_Fled_Scene_Ind,Driver_Safety_Equip_Used,Driver_Vis_Obscured_Type_Cd,Summons_Issued_Cd,Vehiclenumber,Vehicle_Body_Type_Cd,Vehicle_Make_Nm,Vehicle_Maneuver_Type_Cd,Vehicle_Model_Nm,Vehicle_Year_Nbr,Comm_Cargo_Body_Type_Cd,Comm_Vehicle_Body_Type_Cd,Speed_Before,Speed_Posted,Speed_Max_Safe,First_Crash_Event_Cd,Second_Crash_Event_Cd,Third_Crash_Event_Cd,Fourth_Crash_Event_Cd,Most_Harmful_Crash_Event_Cd,Initial_Veh_Impact_Area_Cd,Direction_Of_Travel_Cd,Pass_vehiclenumber,Pass_InjuryType,Pass_age,Pass_gender,Pass_Safety_Equip_Used,Pass_Airbag_Deployment,Pass_Ejected_From_Vehicle,Pass_Ems_Transport_Ind,Bike_VehicleNumber,Bike_InjuryType,Bike_Age,Bike_Gender,Ped_Number,Ped_InjuryType,PED_Age,Ped_Gender,Ped_Action,Ped_Drink,Ped_Cond,Ped_Al_Test,Ped_Drug,Ped_Rflct
25,26,170515221,2017,A,1;2,PDO;A,18;63,Female;Male,12. Following Too Close;1. No Improper Action,1. Deployed - Front;2. Not Deployed,n/a; n/a,1. No Defects;1. No Defects,14. No Distraction;14. No Distraction,1. No Drinking;1. No Drinking,2. No;2. No,1. Not Ejected;1. Not Ejected,No;Yes,No;No,3. Lap and Shoulder Belt;3. Lap and Shoulder Belt,12. Sun or Headlight Glare;1. Not Obscured,1. Yes;1. Yes,1;2,3. Van;22. Truck (SUV),HONDA;MITSUBISHI,5. Slowing or Stopping;5. Slowing or Stopping,ODYSSEY;OUTLANDER,2006;2015,n/a; n/a,n/a; n/a,35;5,45;45,5;5,20. Motor Vehicle In Transport;20. Motor Vehic...,n/a; n/a,n/a; n/a,n/a; n/a,20. Motor Vehicle In Transport;20. Motor Vehic...,12;6,West;West,1,B,18,Female,3. Lap and Shoulder Belt,1. Deployed - Front,1. Not Ejected,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,28,170685247,2017,K,1;2;3,B;K;PDO,29;65;51,Male;Female;Male,40. Fail to Maintain Proper Control;1. No Impr...,8. Deployed - Combination;1. Deployed - Front;...,n/a; n/a; n/a,5. Illness;1. No Defects;1. No Defects,14. No Distraction;14. No Distraction;14. No D...,1. No Drinking;1. No Drinking;1. No Drinking,2. No;2. No;2. No,1. Not Ejected;1. Not Ejected;1. Not Ejected,Yes;NotProvided;NotProvided,No;No;No,3. Lap and Shoulder Belt;3. Lap and Shoulder B...,1. Not Obscured;1. Not Obscured;1. Not Obscured,3. Pending;2. No;2. No,1;2;3,22. Truck (SUV);1. Passenger car;1. Passenger car,FORD;CHRYSLER;TOYOTA,10. Ran Off Road - Left;1. Going Straight Ahea...,EXPEDITION;PT CRUISER;ECHO,2017;2002;2001,n/a; n/a; n/a,n/a; n/a; n/a,45;45;45,45;45;45,n/a;n/a;n/a,13. Curb;20. Motor Vehicle In Transport;40. Th...,28. Ran Off Road; n/a; n/a,35. Cross Median; n/a; n/a,20. Motor Vehicle In Transport; n/a; n/a,20. Motor Vehicle In Transport;20. Motor Vehic...,11;11;2,South;North;North,1,B,19,Female,3. Lap and Shoulder Belt,8. Deployed - Combination,1. Not Ejected,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,29,170695161,2017,B,1;2,B;PDO,67;67,Female;Male,1. No Improper Action;12. Following Too Close,2. Not Deployed;2. Not Deployed,n/a; n/a,1. No Defects;1. No Defects,14. No Distraction;14. No Distraction,1. No Drinking;1. No Drinking,2. No;2. No,1. Not Ejected;1. Not Ejected,No;No,No;No,3. Lap and Shoulder Belt;3. Lap and Shoulder Belt,1. Not Obscured;1. Not Obscured,2. No;1. Yes,1;2,22. Truck (SUV);2. Pick-up Truck,CHRYSLER;FORD,8. Stopped in Traffic Lane;1. Going Straight A...,PACIFICA;F150,2006;2003,n/a; n/a,n/a; n/a,0;15,70;70,0;0,20. Motor Vehicle In Transport;20. Motor Vehic...,n/a; n/a,n/a; n/a,n/a; n/a,20. Motor Vehicle In Transport;20. Motor Vehic...,6;12,South;South,1,B,69,Male,3. Lap and Shoulder Belt,2. Not Deployed,1. Not Ejected,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,49,171945426,2017,K,1;2,K;A,25;33,Male;Male,2. Exceeded Speed Limit;1. No Improper Action,3. n/a;2. Not Deployed,n/a; n/a,9. Unknown;1. No Defects,14. No Distraction;14. No Distraction,6. Unknown;1. No Drinking,3. Unknown;2. No,1. Not Ejected;1. Not Ejected,Yes;No,No;No,5. Helmet;3. Lap and Shoulder Belt,1. Not Obscured;1. Not Obscured,2. No;2. No,1;2,11. Motorcycle;1. Passenger car,YAMAHA;TOYOTA,13. Passing;1. Going Straight Ahead,R1;ECHO,2010;2003,n/a; n/a,n/a; n/a,100;60,60;60,60;60,11. Jersey Wall;20. Motor Vehicle In Transport,20. Motor Vehicle In Transport;28. Ran Off Road,n/a;11. Jersey Wall,n/a; n/a,20. Motor Vehicle In Transport;11. Jersey Wall,12;7,North;North,2,A,32,Female,3. Lap and Shoulder Belt,2. Not Deployed,1. Not Ejected,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,50,172695407,2017,B,1,B,23,Female,40. Fail to Maintain Proper Control,8. Deployed - Combination,4. No Test,8. Other,14. No Distraction,1. No Drinking,3. Unknown,1. Not Ejected,Yes,No,3. Lap and Shoulder Belt,1. Not Obscured,1. Yes,1,1. Passenger car,TOYOTA,9. Ran Off Road - Right,CAMRY,2005,n/a,n/a,60,45,45,28. Ran Off Road,2. Trees,n/a,n/a,2. Trees,12,South,1,B,5,Male,3. Lap and Shoulder Belt,8. Deployed - Combination,1. Not Ejected,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1121947,1121948,260050190,2026,B,1,B,59,Male,1. No Improper Action,2. Not Deployed,2. Breath,1. No Defects,14. No Distraction,4. Drinking - Ability Not Impaired,2. No,1. Not Ejected,No,No,3. Lap and Shoulder Belt,1. Not Obscured,2. No,1,22. Truck (SUV),MITSUBISHI,4. Making U-Turn,Outlander,2013,n/a,n/a,15,45,45,39. Fell/Jumped From Vehicle,n/a,n/a,n/a,39. Fell/Jumped From Vehicle,0,East,1,B,53,Female,3. Lap and Shoulder Belt,2. Not Deployed,3. Totally Ejected,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1121950,1121951,260510357,2026,B,1;2,PDO;C,41;77,Female;Male,11. Did Not Have Right-of-Way;1. No Improper A...,2. Not Deployed;8. Deployed - Combination,4. No Test;4. No Test,1. No Defects;1. No Defects,14. No Distraction;14. No Distraction,1. No Drinking;1. No Drinking,2. No;2. No,1. Not Ejected;1. Not Ejected,No;Yes,No;No,3. Lap and Shoulder Belt;3. Lap and Shoulder Belt,7. Embankment;1. Not Obscured,1. Yes;2. No,1;2,22. Truck (SUV);22. Truck (SUV),SUBA;TOYT,3. Making Left Turn;1. Going Straight Ahead,OUTBACK;LAND CRUISER,2021;2000,n/a; n/a,n/a; n/a,5;0,45;45,0;45,20. Motor Vehicle In Transport;20. Motor Vehic...,n/a; n/a,n/a; n/a,n/a; n/a,20. Motor Vehicle In Transport;20. Motor Vehic...,11;12,West;East,1;2,B;C,11;81,Male;Female,3. Lap and Shoulder Belt;3. Lap and Shoulder Belt,2. Not Deployed;8. Deployed - Combination,1. Not Ejected;1. Not Ejected,No;Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1121952,1121953,260500002,2026,B,1;2,C;B,69;72,Male;Female,11. Did Not Have Right-of-Way;1. No Improper A...,2. Not Deployed;1. Deployed - Front,4. No Test;4. No Test,1. No Defects;1. No Defects,14. No Distraction;14. No Distraction,1. No Drinking;1. No Drinking,2. No;2. No,1. Not Ejected;1. Not Ejected,No;No,No;No,8. No Restraint Used;3. Lap and Shoulder Belt,1. Not Obscured;1. Not Obscured,1. Yes;2. No,1;2,1. Passenger car;22. Truck (SUV),FORD;NISS,16. Entering Street From Parking Lot;1. Going ...,LGT CONVTNL 'F';ROGUE,1999;2020,n/a; n/a,n/a; n/a,15;60,60;60,60;60,20. Motor Vehicle In Transport;20. Motor Vehic...,n/a; n/a,n/a; n/a,n/a; n/a,20. Motor Vehicle In Transport;20. Motor Vehic...,6;12,West;West,2,B,76,Male,3. Lap and Shoulder Belt,1. Deployed - Front,1. Not Ejected,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1121955,1121956,260500119,2026,C,1;2,PDO;PDO,18;17,Male;Male,1. No Improper Action;1. No Improper Action,8. Deployed - Combination;8. Deployed - Combin...,4. No Test;4. No Test,1. No Defects;1. No Defects,14. No Distraction;14. No Distraction,1. No Drinking;1. No Drinking,2. No;2. No,1. Not Ejected;1. Not Ejected,No;No,No;No,3. Lap and Shoulder Belt;3. Lap and Shoulder Belt,1. Not Obscured;1. Not Obscured,2. No;2. No,1;2,1. Passenger car;1. Passenger car,audi;VOLKSWAGEN,1. Going Straight Ahead;5. Slowing or Stopping,"a3;GOLF, GOLF R, GOLF ALLTRACK, E-GOLF, GOLF G...",2023;2017,n/a; n/a,n/a; n/a,15;30,35;35,35;35,20. Motor Vehicle In Transport;20. Motor Vehic...,n/a; n/a,n/a; n/a,n/a; n/a,20. Motor Vehicle In Transport;20. Motor Vehic...,5;12,North;West,1,C,18,Female,3. Lap and Shoulder Belt,8. Deployed - Combination,1. Not Ejected,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1121974,1121975,260030148,2026,C,1;2,PDO;PDO,42;40,Male;Male,12. Following Too Close;1. No Improper Action,2. Not Deployed;2. Not Deployed,4. No Test;4. No Test,9. Unknown;1. No Defects,14. No Distraction;14. No Distraction,1. No Drinking;1. No Drinking,2. No;2. No,1. Not Ejected;1. Not Ejected,No;No,No;No,3. Lap and Shoulder Belt;3. Lap and Shoulder Belt,1. Not Obscured;1. Not Obscured,1. Yes;2. No,1;2,22. Truck (SUV);1. Passenger car,DODGE;ACURA,1. Going Straight Ahead;5. Slowing or Stopping,Durango;Integra,2019;2023,n/a; n/a,n/a; n/a,n/a;n/a,35;35,35;35,20. Motor Vehicle In Transport;20. Motor Vehic...,n/a; n/a,n/a; n/a,n/a; n/a,20. Motor Vehicle In Transport;20. Motor Vehic...,12;6,West;West,2,C,40,Female,3. Lap and Shoulder Belt,2. Not Deployed,1. Not Ejected,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
basic['Crash Year'].unique()

array([2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026])

In [59]:
detail['Pass_vehiclenumber'].unique()

<StringArray>
[                                                  nan,
                                                   '1',
                                                   '2',
                                               '1;1;1',
                                                   '3',
                                                 '2;2',
                                                 '1;1',
                                               '2;2;3',
                                         '1;1;1;1;1;1',
                                               '2;2;2',
 ...
                                         '1;1;1;2;2;3',
                                           '2;3;3;5;6',
                                             '1;5;5;5',
                                       '1;1;1;1;1;1;3',
                             '2;2;2;2;2;2;2;2;2;2;2;2',
                                       '1;2;2;2;2;2;3',
                           '1;1;1;1;1;1;1;1;1;1;1;2;2',
                                               '2;1;1',
 '2;2;2;2;2;2;2;2;2;2;2;2;2;2;2;2;2;2;2;2;2;2;2;2;2;2',
                                           '2;2;3;4;4']
Length: 252, dtype: str